language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo64-7.0
  - Pharo-7.0
  - Pharo-6.1
  - Pharo-6.0
  - Pharo-5.0
  
matrix:
  allow_failures:
  - smalltalk: Pharo64-7.0
  - smalltalk: Pharo-7.0

  fast_finish: true
